version: "0.1.0-{build}-{branch}"

# Appveyor configuration template for Rust using rustup for Rust installation
# https://github.com/starkat99/appveyor-rust

os: Visual Studio 2017

environment:
  global:
    PROJECT_NAME: sarcasm
    RUST_BACKTRACE: full
  matrix:

    # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc

    # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
  - rustup update
  - rustc -vV
  - cargo -vV

build: false

cache:
  - '%USERPROFILE%\.cache\sccache -> rust-toolchain,.appveyor.yml'
  - '%USERPROFILE%\.cargo -> rust-toolchain,.appveyor.yml'
  - '%USERPROFILE%\.rustup -> rust-toolchain,.appveyor.yml'
  - 'target -> rust-toolchain,.appveyor.yml'

test_script:
  - cargo build --verbose --all --all-targets %cargoflags%
  - cargo test --verbose --all --all-targets --no-fail-fast %cargoflags%
  - cargo doc --verbose --all --no-deps %cargoflags%

before_deploy:
  - cargo build --release --package sarcasm --bin sarcasm
  - mkdir staging
  - copy target\release\sarcasm.exe staging
  - cd staging
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  provider: GitHub
  description: "Sarcasm release $(APPVEYOR_REPO_TAG_NAME)."
  auth_token:
    secure: Fcj47MHgcGwm6DDVm11BAjN07dYxYyZiSXggqLBm1CPpQuA+JAthtna5lus2tSaJ
  on:
    target: x86_64-pc-windows-msvc
    appveyor_repo_tag: true

